/*
 * This file is part of the Combatant Client distribution.
 * Copyright (c) 2026 pivosos2007.
 *
 * Licensed under the GNU General Public License v3.0.
 */

package combatant.client.render.engine.material;

import com.mojang.blaze3d.GpuFormat;
import com.mojang.blaze3d.pipeline.BindGroupLayout;
import com.mojang.blaze3d.platform.NativeImage;
import com.mojang.blaze3d.systems.RenderPass;
import com.mojang.blaze3d.systems.RenderSystem;
import com.mojang.blaze3d.textures.GpuSampler;
import com.mojang.blaze3d.textures.GpuTexture;
import com.mojang.blaze3d.textures.GpuTextureView;
import combatant.client.mixins.accessors.SpriteAnimationStateAccessor;
import combatant.client.util.logging.DebugLog;
import net.minecraft.client.renderer.texture.SpriteContents;
import net.minecraft.client.renderer.texture.TextureAtlasSprite;
import net.minecraft.client.resources.metadata.animation.AnimationFrame;
import net.minecraft.client.resources.metadata.animation.AnimationMetadataSection;
import net.minecraft.resources.Identifier;
import net.minecraft.server.packs.resources.Resource;
import net.minecraft.server.packs.resources.ResourceManager;

import java.io.IOException;
import java.util.ArrayList;
import java.util.EnumMap;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * Combatant companion atlases for Sodium's block atlas.
 *
 * <p>The companion textures use the exact same stitched x/y layout as the Minecraft block atlas,
 * therefore the UV generated by Sodium selects the same logical sprite in every material map.
 * Animated maps do not run an independent clock: after vanilla advances its AnimationState this
 * class reads the exact frame/sub-frame chosen by Minecraft and uploads the corresponding material
 * frame (including interpolation when the base sprite requested interpolation).</p>
 */
public final class MaterialAtlasManager {
    public static final String ALBEDO_SAMPLER = "u_CombatantAlbedoAtlas";
    public static final String NORMAL_HEIGHT_SAMPLER = "u_CombatantNormalHeightAtlas";
    public static final String SURFACE_SAMPLER = "u_CombatantSurfaceAtlas";
    public static final String SPECULAR_SAMPLER = "u_CombatantSpecularAtlas";

    public static final BindGroupLayout BIND_GROUP = BindGroupLayout.builder()
            .withSampler(ALBEDO_SAMPLER)
            .withSampler(NORMAL_HEIGHT_SAMPLER)
            .withSampler(SURFACE_SAMPLER)
            .withSampler(SPECULAR_SAMPLER)
            .build();

    private static final MaterialAtlasManager GLOBAL = new MaterialAtlasManager();
    private static final int USAGE = GpuTexture.USAGE_COPY_DST | GpuTexture.USAGE_TEXTURE_BINDING;

    private AtlasTexture albedo;
    private AtlasTexture normalHeight;
    private AtlasTexture surface;
    private AtlasTexture specular;
    private final List<AnimatedBinding> animated = new ArrayList<>();
    private int width;
    private int height;
    private int maxMipLevel;
    private long generation;

    public static MaterialAtlasManager global() {
        return GLOBAL;
    }

    public synchronized long generation() {
        return generation;
    }

    public synchronized boolean ready() {
        return albedo != null && normalHeight != null && surface != null && specular != null;
    }

    public synchronized GpuTextureView albedoView() { return albedo != null ? albedo.view() : null; }
    public synchronized GpuTextureView normalHeightView() { return normalHeight != null ? normalHeight.view() : null; }
    public synchronized GpuTextureView surfaceView() { return surface != null ? surface.view() : null; }
    public synchronized GpuTextureView specularView() { return specular != null ? specular.view() : null; }

    public synchronized void rebuild(List<TextureAtlasSprite> sprites,
                                     List<SpriteContents.AnimationState> animationStates,
                                     int atlasWidth,
                                     int atlasHeight,
                                     int atlasMaxMipLevel) {
        RenderSystem.assertOnRenderThread();
        releaseInternal();

        ResourceManager resources = MaterialRegistry.global().resources();
        if (resources == null || sprites == null || atlasWidth <= 0 || atlasHeight <= 0) {
            MaterialRegistry.global().installGpuMapAvailability(Map.of());
            return;
        }

        this.width = atlasWidth;
        this.height = atlasHeight;
        this.maxMipLevel = Math.max(0, atlasMaxMipLevel);

        try (NativeImage albedoImage = filled(atlasWidth, atlasHeight, argb(255, 255, 255, 255));
             NativeImage normalHeightImage = filled(atlasWidth, atlasHeight, argb(0, 128, 128, 255));
             NativeImage surfaceImage = filled(atlasWidth, atlasHeight, argb(0, 255, 184, 0));
             NativeImage specularImage = filled(atlasWidth, atlasHeight, argb(0, 10, 0, 0))) {

            Map<Identifier, Integer> usableBySprite = new HashMap<>();
            int animationIndex = 0;
            for (TextureAtlasSprite sprite : sprites) {
                SpriteContents.AnimationState baseState = null;
                if (sprite.isAnimated()) {
                    if (animationIndex < animationStates.size()) {
                        baseState = animationStates.get(animationIndex);
                    }
                    animationIndex++;
                }

                MaterialSurfaceDescriptor descriptor = MaterialRegistry.global().resolveAtlas(sprite);
                PreparedSprite prepared = prepareSprite(resources, sprite, descriptor, baseState);
                usableBySprite.put(sprite.contents().name(), prepared.usableMask());
                if (prepared.usableMask() == 0) {
                    prepared.close();
                    continue;
                }

                FrameSample initial = prepared.sample(baseState);
                blit(initial.albedo(), albedoImage, sprite.getX(), sprite.getY());
                blit(initial.normalHeight(), normalHeightImage, sprite.getX(), sprite.getY());
                blit(initial.surface(), surfaceImage, sprite.getX(), sprite.getY());
                blit(initial.specular(), specularImage, sprite.getX(), sprite.getY());
                initial.close();

                if (baseState != null && prepared.timeline() != null) {
                    animated.add(new AnimatedBinding(sprite, baseState, prepared));
                } else {
                    prepared.close();
                }
            }

            MaterialRegistry.global().installGpuMapAvailability(usableBySprite);
            albedo = create("Combatant material albedo atlas", albedoImage, maxMipLevel, MipKind.COLOR);
            normalHeight = create("Combatant material normal-height atlas", normalHeightImage, maxMipLevel, MipKind.NORMAL_HEIGHT);
            surface = create("Combatant material surface atlas", surfaceImage, maxMipLevel, MipKind.SCALAR);
            specular = create("Combatant material specular atlas", specularImage, maxMipLevel, MipKind.SCALAR);
            generation++;
            DebugLog.renderThread("[Materials] companion block atlases ready: %dx%d, animated=%d, generation=%d",
                    atlasWidth, atlasHeight, animated.size(), generation);
        } catch (Throwable error) {
            DebugLog.warn("[Materials] failed to build companion atlases: %s: %s",
                    error.getClass().getSimpleName(), error.getMessage());
            releaseInternal();
            MaterialRegistry.global().installGpuMapAvailability(Map.of());
        }
    }

    /** Called after vanilla TextureAtlas.cycleAnimationFrames(), using vanilla's exact state. */
    public synchronized void synchronizeAnimations() {
        if (!ready() || animated.isEmpty()) return;
        RenderSystem.assertOnRenderThread();
        for (AnimatedBinding binding : animated) {
            if (!binding.state().needsToDraw()) continue;
            try (FrameSample sample = binding.prepared().sample(binding.state())) {
                writeFrame(albedo, sample.albedo(), binding.sprite());
                writeFrame(normalHeight, sample.normalHeight(), binding.sprite());
                writeFrame(surface, sample.surface(), binding.sprite());
                writeFrame(specular, sample.specular(), binding.sprite());
            } catch (Throwable error) {
                DebugLog.warnOnChange(
                        "combatant.material.animation." + binding.sprite().contents().name(),
                        error.getClass().getSimpleName() + "|" + error.getMessage(),
                        "[Materials] animated material update failed for %s: %s: %s",
                        binding.sprite().contents().name(), error.getClass().getSimpleName(), error.getMessage()
                );
            }
        }
    }

    public synchronized void bind(RenderPass pass, GpuSampler sampler, GpuTextureView fallback) {
        GpuTextureView albedoView = ready() ? albedo.view() : fallback;
        GpuTextureView normalView = ready() ? normalHeight.view() : fallback;
        GpuTextureView surfaceView = ready() ? surface.view() : fallback;
        GpuTextureView specularView = ready() ? specular.view() : fallback;
        pass.bindTexture(ALBEDO_SAMPLER, albedoView, sampler);
        pass.bindTexture(NORMAL_HEIGHT_SAMPLER, normalView, sampler);
        pass.bindTexture(SURFACE_SAMPLER, surfaceView, sampler);
        pass.bindTexture(SPECULAR_SAMPLER, specularView, sampler);
    }

    public synchronized void release() {
        RenderSystem.assertOnRenderThread();
        releaseInternal();
        MaterialRegistry.global().installGpuMapAvailability(Map.of());
        generation++;
    }

    private void releaseInternal() {
        for (AnimatedBinding binding : animated) {
            binding.prepared().close();
        }
        animated.clear();
        close(albedo);
        close(normalHeight);
        close(surface);
        close(specular);
        albedo = null;
        normalHeight = null;
        surface = null;
        specular = null;
        width = 0;
        height = 0;
        maxMipLevel = 0;
    }

    private static AtlasTexture create(String label, NativeImage image, int maxMipLevel, MipKind kind) {
        int mipLevels = Math.max(1, maxMipLevel + 1);
        GpuTexture texture = RenderSystem.getDevice().createTexture(
                label, USAGE, GpuFormat.RGBA8_UNORM, image.getWidth(), image.getHeight(), 1, mipLevels
        );
        NativeImage level = copyImage(image);
        try {
            for (int mip = 0; mip < mipLevels; mip++) {
                RenderSystem.getDevice().createCommandEncoder().writeToTexture(texture, level, mip, 0, 0, 0);
                if (mip + 1 < mipLevels) {
                    NativeImage next = downsample(level, kind);
                    level.close();
                    level = next;
                }
            }
        } finally {
            level.close();
        }
        return new AtlasTexture(texture, RenderSystem.getDevice().createTextureView(texture), mipLevels, kind);
    }

    /** Uploads the exact vanilla animation state to every companion mip, not just level zero. */
    private static void writeFrame(AtlasTexture atlas, NativeImage frame, TextureAtlasSprite sprite) {
        NativeImage level = copyImage(frame);
        try {
            for (int mip = 0; mip < atlas.mipLevels(); mip++) {
                RenderSystem.getDevice().createCommandEncoder().writeToTexture(
                        atlas.texture(), level, mip, 0, sprite.getX() >> mip, sprite.getY() >> mip
                );
                if (mip + 1 < atlas.mipLevels()) {
                    NativeImage next = downsample(level, atlas.kind());
                    level.close();
                    level = next;
                }
            }
        } finally {
            level.close();
        }
    }

    private static NativeImage copyImage(NativeImage source) {
        NativeImage copy = new NativeImage(source.getWidth(), source.getHeight(), false);
        copy.copyRect(source, 0, 0, 0, 0, source.getWidth(), source.getHeight(), false, false);
        return copy;
    }

    private static NativeImage downsample(NativeImage source, MipKind kind) {
        int width = Math.max(1, source.getWidth() >> 1);
        int height = Math.max(1, source.getHeight() >> 1);
        NativeImage out = new NativeImage(width, height, false);
        for (int y = 0; y < height; y++) {
            for (int x = 0; x < width; x++) {
                int p0 = source.getPixel(Math.min(source.getWidth() - 1, x * 2), Math.min(source.getHeight() - 1, y * 2));
                int p1 = source.getPixel(Math.min(source.getWidth() - 1, x * 2 + 1), Math.min(source.getHeight() - 1, y * 2));
                int p2 = source.getPixel(Math.min(source.getWidth() - 1, x * 2), Math.min(source.getHeight() - 1, y * 2 + 1));
                int p3 = source.getPixel(Math.min(source.getWidth() - 1, x * 2 + 1), Math.min(source.getHeight() - 1, y * 2 + 1));
                out.setPixel(x, y, kind == MipKind.NORMAL_HEIGHT
                        ? averageNormalHeight(p0, p1, p2, p3)
                        : averageArgb(p0, p1, p2, p3));
            }
        }
        return out;
    }

    private static int averageArgb(int a, int b, int c, int d) {
        return argb(
                (alpha(a) + alpha(b) + alpha(c) + alpha(d) + 2) / 4,
                (red(a) + red(b) + red(c) + red(d) + 2) / 4,
                (green(a) + green(b) + green(c) + green(d) + 2) / 4,
                (blue(a) + blue(b) + blue(c) + blue(d) + 2) / 4
        );
    }

    private static int averageNormalHeight(int a, int b, int c, int d) {
        float x = 0.0f, y = 0.0f, z = 0.0f;
        int[] pixels = {a, b, c, d};
        int h = 0;
        for (int pixel : pixels) {
            x += red(pixel) / 127.5f - 1.0f;
            y += green(pixel) / 127.5f - 1.0f;
            z += blue(pixel) / 127.5f - 1.0f;
            h += alpha(pixel);
        }
        float inv = 1.0f / (float)Math.sqrt(Math.max(1.0e-8f, x * x + y * y + z * z));
        return argb(
                (h + 2) / 4,
                unorm(x * inv * 0.5f + 0.5f),
                unorm(y * inv * 0.5f + 0.5f),
                unorm(z * inv * 0.5f + 0.5f)
        );
    }

    private static PreparedSprite prepareSprite(ResourceManager resources,
                                                TextureAtlasSprite sprite,
                                                MaterialSurfaceDescriptor descriptor,
                                                SpriteContents.AnimationState state) throws IOException {
        Identifier spriteId = sprite.contents().name();
        int frameWidth = sprite.contents().width();
        int frameHeight = sprite.contents().height();
        BaseAnimation base = loadBaseAnimation(resources, spriteId, frameWidth, frameHeight, sprite.isAnimated());

        EnumMap<MaterialTextureSemantic, NativeImage> loaded = new EnumMap<>(MaterialTextureSemantic.class);
        int usableMask = 0;
        try {
            for (Map.Entry<MaterialTextureSemantic, Identifier> entry : descriptor.textures().asMap().entrySet()) {
                Optional<Resource> resource = resources.getResource(entry.getValue());
                if (resource.isEmpty()) continue;
                NativeImage image;
                try (var stream = resource.get().open()) {
                    image = NativeImage.read(stream);
                }
                if (!compatible(image, base, frameWidth, frameHeight)) {
                    int invalidWidth = image.getWidth();
                    int invalidHeight = image.getHeight();
                    image.close();
                    DebugLog.warnOnce(
                            "combatant.material.map.dimensions." + entry.getValue(),
                            "[Materials] ignoring %s for %s: %dx%d does not match base sheet %dx%d or frame %dx%d",
                            entry.getValue(), spriteId, invalidWidth, invalidHeight,
                            base.sheetWidth(), base.sheetHeight(), frameWidth, frameHeight
                    );
                    continue;
                }
                loaded.put(entry.getKey(), image);
            }

            NativeImage albedo = new NativeImage(base.sheetWidth(), base.sheetHeight(), false);
            NativeImage normalHeight = new NativeImage(base.sheetWidth(), base.sheetHeight(), false);
            NativeImage surface = new NativeImage(base.sheetWidth(), base.sheetHeight(), false);
            NativeImage specular = new NativeImage(base.sheetWidth(), base.sheetHeight(), false);

            int declared = descriptor.gpuPresenceMask8();
            for (int y = 0; y < base.sheetHeight(); y++) {
                for (int x = 0; x < base.sheetWidth(); x++) {
                    PixelSet px = canonicalPixel(loaded, descriptor, base, frameWidth, frameHeight, x, y);
                    albedo.setPixel(x, y, px.albedo());
                    normalHeight.setPixel(x, y, px.normalHeight());
                    surface.setPixel(x, y, px.surface());
                    specular.setPixel(x, y, px.specular());
                }
            }

            usableMask = usableMask(loaded, declared);
            if (sprite.isAnimated() && base.timeline() == null) {
                usableMask = 0;
            }
            return new PreparedSprite(
                    base.timeline(), frameWidth, frameHeight, base.sheetWidth(), base.sheetHeight(),
                    albedo, normalHeight, surface, specular, usableMask
            );
        } finally {
            for (NativeImage image : loaded.values()) image.close();
        }
    }

    private static int usableMask(Map<MaterialTextureSemantic, NativeImage> maps, int declared) {
        int mask = 0;
        if (maps.containsKey(MaterialTextureSemantic.NORMAL) || maps.containsKey(MaterialTextureSemantic.LABPBR_NORMAL)) mask |= 1 << 0;
        if (maps.containsKey(MaterialTextureSemantic.AMBIENT_OCCLUSION) || maps.containsKey(MaterialTextureSemantic.ORM) || maps.containsKey(MaterialTextureSemantic.LABPBR_NORMAL)) mask |= 1 << 1;
        if (maps.containsKey(MaterialTextureSemantic.ROUGHNESS) || maps.containsKey(MaterialTextureSemantic.ORM) || maps.containsKey(MaterialTextureSemantic.LABPBR_SPECULAR)) mask |= 1 << 2;
        if (maps.containsKey(MaterialTextureSemantic.METALLIC) || maps.containsKey(MaterialTextureSemantic.ORM) || maps.containsKey(MaterialTextureSemantic.LABPBR_SPECULAR)) mask |= 1 << 3;
        if (maps.containsKey(MaterialTextureSemantic.SPECULAR) || maps.containsKey(MaterialTextureSemantic.LABPBR_SPECULAR)) mask |= 1 << 4;
        if (maps.containsKey(MaterialTextureSemantic.EMISSIVE) || maps.containsKey(MaterialTextureSemantic.LABPBR_SPECULAR)) mask |= 1 << 5;
        if (maps.containsKey(MaterialTextureSemantic.HEIGHT) || maps.containsKey(MaterialTextureSemantic.LABPBR_NORMAL)) mask |= 1 << 6;
        if (maps.containsKey(MaterialTextureSemantic.ALBEDO)) mask |= 1 << 7;
        return mask & declared;
    }

    private static PixelSet canonicalPixel(Map<MaterialTextureSemantic, NativeImage> maps,
                                           MaterialSurfaceDescriptor descriptor,
                                           BaseAnimation base,
                                           int frameWidth,
                                           int frameHeight,
                                           int x,
                                           int y) {
        int albedo = argb(255, 255, 255, 255);
        int nr = 128, ng = 128, nb = 255, height = 0;
        int ao = 255;
        int roughness = unorm(descriptor.roughness());
        int metallic = unorm(descriptor.metallic());
        int emission = unorm(Math.min(descriptor.emission(), 1.0f));
        int f0 = unorm(descriptor.dielectricF0());
        int transmission = unorm(descriptor.transmission());
        int subsurface = unorm(descriptor.subsurface());
        int clearcoat = unorm(descriptor.clearcoat());

        NativeImage image = maps.get(MaterialTextureSemantic.ALBEDO);
        if (image != null) albedo = sample(image, base, frameWidth, frameHeight, x, y);

        image = maps.get(MaterialTextureSemantic.NORMAL);
        if (image != null) {
            int p = sample(image, base, frameWidth, frameHeight, x, y);
            nr = red(p); ng = green(p); nb = blue(p);
        } else if ((image = maps.get(MaterialTextureSemantic.LABPBR_NORMAL)) != null) {
            int p = sample(image, base, frameWidth, frameHeight, x, y);
            nr = red(p); ng = green(p); nb = reconstructNormalZ(nr, ng);
            ao = blue(p);
            height = alpha(p);
        }

        image = maps.get(MaterialTextureSemantic.AMBIENT_OCCLUSION);
        if (image != null) ao = luminance(sample(image, base, frameWidth, frameHeight, x, y));
        image = maps.get(MaterialTextureSemantic.ORM);
        if (image != null) {
            int p = sample(image, base, frameWidth, frameHeight, x, y);
            ao = red(p); roughness = green(p); metallic = blue(p);
        }
        image = maps.get(MaterialTextureSemantic.ROUGHNESS);
        if (image != null) roughness = luminance(sample(image, base, frameWidth, frameHeight, x, y));
        image = maps.get(MaterialTextureSemantic.METALLIC);
        if (image != null) metallic = luminance(sample(image, base, frameWidth, frameHeight, x, y));
        image = maps.get(MaterialTextureSemantic.SPECULAR);
        if (image != null) f0 = luminance(sample(image, base, frameWidth, frameHeight, x, y));
        image = maps.get(MaterialTextureSemantic.EMISSIVE);
        if (image != null) emission = maxRgb(sample(image, base, frameWidth, frameHeight, x, y));
        image = maps.get(MaterialTextureSemantic.HEIGHT);
        if (image != null) height = luminance(sample(image, base, frameWidth, frameHeight, x, y));

        image = maps.get(MaterialTextureSemantic.LABPBR_SPECULAR);
        if (image != null) {
            int p = sample(image, base, frameWidth, frameHeight, x, y);
            float smooth = red(p) / 255.0f;
            roughness = unorm((1.0f - smooth) * (1.0f - smooth));
            int g = green(p);
            if (g < 230) {
                f0 = Math.max(f0, g);
                int b = blue(p);
                if (b >= 65) subsurface = Math.max(subsurface, Math.round((b - 64) * (255.0f / 191.0f)));
            } else {
                metallic = 255;
                f0 = Math.max(f0, labMetalF0(g));
            }
            int a = alpha(p);
            if (a != 255) emission = Math.max(emission, a);
        }

        return new PixelSet(
                albedo,
                argb(height, nr, ng, nb),
                argb(emission, ao, roughness, metallic),
                argb(clearcoat, f0, transmission, subsurface)
        );
    }

    private static int labMetalF0(int green) {
        if (green >= 238) return 255;
        return switch (Math.max(0, Math.min(7, green - 230))) {
            case 0 -> 195; // iron
            case 1 -> 230; // gold
            case 2 -> 250; // aluminium
            case 3 -> 201; // chrome
            case 4 -> 224; // copper
            case 5 -> 213; // lead
            case 6 -> 225; // platinum
            default -> 249; // silver
        };
    }

    private static BaseAnimation loadBaseAnimation(ResourceManager resources,
                                                   Identifier spriteId,
                                                   int frameWidth,
                                                   int frameHeight,
                                                   boolean animated) throws IOException {
        Identifier baseId = Identifier.fromNamespaceAndPath(
                spriteId.getNamespace(), "textures/" + spriteId.getPath() + ".png"
        );
        Optional<Resource> resource = resources.getResource(baseId);
        if (resource.isEmpty()) {
            return new BaseAnimation(frameWidth, frameHeight, null);
        }
        int sheetWidth;
        int sheetHeight;
        try (var stream = resource.get().open(); NativeImage image = NativeImage.read(stream)) {
            sheetWidth = image.getWidth();
            sheetHeight = image.getHeight();
        }
        if (!animated) return new BaseAnimation(sheetWidth, sheetHeight, null);

        Optional<AnimationMetadataSection> metadata = resource.get().metadata().getSection(AnimationMetadataSection.TYPE);
        if (metadata.isEmpty()) {
            DebugLog.warnOnce("combatant.material.animation.metadata." + spriteId,
                    "[Materials] animated sprite %s has no readable animation metadata; companion maps disabled", spriteId);
            return new BaseAnimation(sheetWidth, sheetHeight, null);
        }
        AnimationMetadataSection section = metadata.get();
        int columns = Math.max(1, sheetWidth / frameWidth);
        int rows = Math.max(1, sheetHeight / frameHeight);
        int frameCount = columns * rows;
        List<FrameInfo> frames = new ArrayList<>();
        if (section.frames().isPresent()) {
            for (AnimationFrame frame : section.frames().get()) {
                if (frame.index() >= 0 && frame.index() < frameCount) {
                    frames.add(new FrameInfo(frame.index(), Math.max(1, frame.timeOr(section.defaultFrameTime()))));
                }
            }
        } else {
            for (int i = 0; i < frameCount; i++) {
                frames.add(new FrameInfo(i, Math.max(1, section.defaultFrameTime())));
            }
        }
        Timeline timeline = frames.isEmpty() ? null : new Timeline(List.copyOf(frames), columns, section.interpolatedFrames());
        return new BaseAnimation(sheetWidth, sheetHeight, timeline);
    }

    private static boolean compatible(NativeImage image, BaseAnimation base, int frameWidth, int frameHeight) {
        return (image.getWidth() == base.sheetWidth() && image.getHeight() == base.sheetHeight())
                || (image.getWidth() == frameWidth && image.getHeight() == frameHeight);
    }

    private static int sample(NativeImage image, BaseAnimation base, int frameWidth, int frameHeight, int x, int y) {
        if (image.getWidth() == frameWidth && image.getHeight() == frameHeight) {
            return image.getPixel(Math.floorMod(x, frameWidth), Math.floorMod(y, frameHeight));
        }
        return image.getPixel(x, y);
    }

    private static NativeImage filled(int width, int height, int color) {
        NativeImage image = new NativeImage(width, height, false);
        image.fillRect(0, 0, width, height, color);
        return image;
    }

    private static void blit(NativeImage source, NativeImage target, int dstX, int dstY) {
        if (source == null) return;
        target.copyRect(source, 0, 0, dstX, dstY, source.getWidth(), source.getHeight(), false, false);
    }

    private static NativeImage frame(NativeImage sheet, Timeline timeline, int sequenceFrame,
                                     int frameWidth, int frameHeight, int sheetWidth, int sheetHeight,
                                     int subFrame) {
        NativeImage output = new NativeImage(frameWidth, frameHeight, false);
        if (timeline == null) {
            output.copyRect(sheet, 0, 0, 0, 0, frameWidth, frameHeight, false, false);
            return output;
        }
        int sequence = Math.floorMod(sequenceFrame, timeline.frames().size());
        FrameInfo current = timeline.frames().get(sequence);
        FrameInfo next = timeline.frames().get((sequence + 1) % timeline.frames().size());
        int currentX = (current.index() % timeline.columns()) * frameWidth;
        int currentY = (current.index() / timeline.columns()) * frameHeight;
        float blend = timeline.interpolate()
                ? Math.max(0.0f, Math.min(1.0f, subFrame / (float) Math.max(1, current.time())))
                : 0.0f;
        int nextX = (next.index() % timeline.columns()) * frameWidth;
        int nextY = (next.index() / timeline.columns()) * frameHeight;
        for (int y = 0; y < frameHeight; y++) {
            for (int x = 0; x < frameWidth; x++) {
                int a = sheet.getPixel(Math.min(sheetWidth - 1, currentX + x), Math.min(sheetHeight - 1, currentY + y));
                if (blend <= 0.0f || current.index() == next.index()) {
                    output.setPixel(x, y, a);
                } else {
                    int b = sheet.getPixel(Math.min(sheetWidth - 1, nextX + x), Math.min(sheetHeight - 1, nextY + y));
                    output.setPixel(x, y, lerpArgb(a, b, blend));
                }
            }
        }
        return output;
    }

    private static int lerpArgb(int a, int b, float t) {
        return argb(
                lerp(alpha(a), alpha(b), t),
                lerp(red(a), red(b), t),
                lerp(green(a), green(b), t),
                lerp(blue(a), blue(b), t)
        );
    }

    private static int lerp(int a, int b, float t) {
        return Math.round(a + (b - a) * t);
    }

    private static int reconstructNormalZ(int r, int g) {
        float x = r / 255.0f * 2.0f - 1.0f;
        float y = g / 255.0f * 2.0f - 1.0f;
        float z = (float) Math.sqrt(Math.max(0.0f, 1.0f - x * x - y * y));
        return unorm(z);
    }

    private static int luminance(int argb) {
        return Math.round(red(argb) * 0.2126f + green(argb) * 0.7152f + blue(argb) * 0.0722f);
    }

    private static int maxRgb(int argb) {
        return Math.max(red(argb), Math.max(green(argb), blue(argb)));
    }

    private static int unorm(float value) {
        return Math.round(Math.max(0.0f, Math.min(1.0f, value)) * 255.0f);
    }

    private static int argb(int a, int r, int g, int b) {
        return ((a & 255) << 24) | ((r & 255) << 16) | ((g & 255) << 8) | (b & 255);
    }

    private static int alpha(int p) { return (p >>> 24) & 255; }
    private static int red(int p) { return (p >>> 16) & 255; }
    private static int green(int p) { return (p >>> 8) & 255; }
    private static int blue(int p) { return p & 255; }

    private static void close(AtlasTexture texture) {
        if (texture == null) return;
        try { texture.view().close(); } catch (Throwable ignored) { }
        try { texture.texture().close(); } catch (Throwable ignored) { }
    }

    private enum MipKind { COLOR, NORMAL_HEIGHT, SCALAR }
    private record AtlasTexture(GpuTexture texture, GpuTextureView view, int mipLevels, MipKind kind) { }
    private record PixelSet(int albedo, int normalHeight, int surface, int specular) { }
    private record FrameInfo(int index, int time) { }
    private record Timeline(List<FrameInfo> frames, int columns, boolean interpolate) { }
    private record BaseAnimation(int sheetWidth, int sheetHeight, Timeline timeline) { }
    private record AnimatedBinding(TextureAtlasSprite sprite, SpriteContents.AnimationState state, PreparedSprite prepared) { }

    private static final class PreparedSprite implements AutoCloseable {
        private final Timeline timeline;
        private final int frameWidth;
        private final int frameHeight;
        private final int sheetWidth;
        private final int sheetHeight;
        private final NativeImage albedo;
        private final NativeImage normalHeight;
        private final NativeImage surface;
        private final NativeImage specular;
        private final int usableMask;

        private PreparedSprite(Timeline timeline, int frameWidth, int frameHeight, int sheetWidth, int sheetHeight,
                               NativeImage albedo, NativeImage normalHeight, NativeImage surface, NativeImage specular,
                               int usableMask) {
            this.timeline = timeline;
            this.frameWidth = frameWidth;
            this.frameHeight = frameHeight;
            this.sheetWidth = sheetWidth;
            this.sheetHeight = sheetHeight;
            this.albedo = albedo;
            this.normalHeight = normalHeight;
            this.surface = surface;
            this.specular = specular;
            this.usableMask = usableMask;
        }

        private Timeline timeline() { return timeline; }
        private int usableMask() { return usableMask; }

        private FrameSample sample(SpriteContents.AnimationState state) {
            int sequence = 0;
            int subFrame = 0;
            if (state != null) {
                SpriteAnimationStateAccessor accessor = (SpriteAnimationStateAccessor) (Object) state;
                sequence = accessor.combatant$getFrame();
                subFrame = accessor.combatant$getSubFrame();
            }
            return new FrameSample(
                    frame(albedo, timeline, sequence, frameWidth, frameHeight, sheetWidth, sheetHeight, subFrame),
                    frame(normalHeight, timeline, sequence, frameWidth, frameHeight, sheetWidth, sheetHeight, subFrame),
                    frame(surface, timeline, sequence, frameWidth, frameHeight, sheetWidth, sheetHeight, subFrame),
                    frame(specular, timeline, sequence, frameWidth, frameHeight, sheetWidth, sheetHeight, subFrame)
            );
        }

        @Override
        public void close() {
            albedo.close();
            normalHeight.close();
            surface.close();
            specular.close();
        }
    }

    private record FrameSample(NativeImage albedo, NativeImage normalHeight, NativeImage surface, NativeImage specular)
            implements AutoCloseable {
        @Override
        public void close() {
            albedo.close();
            normalHeight.close();
            surface.close();
            specular.close();
        }
    }
}
