/*
 * This file is part of the Combatant Client distribution.
 * Copyright (c) 2026 pivosos2007.
 *
 * Licensed under the GNU General Public License v3.0.
 */

package combatant.client.runtime.discovery;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertTrue;

final class CombatantIndexTest {
    @Test
    void containsTopLevelAndNestedBuiltinComponents() {
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.visuals.Zoom"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.combat.Surround"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.player.Blink"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.misc.PopCounter"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.misc.AutoRespawn"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.movement.FastFall"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.movement.AntiVoid"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.player.AutoMend"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.movement.Jesus"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.movement.HoleSnap"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.misc.AutoLog"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.misc.VisualRange"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.movement.FastSwim"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.combat.AntiWeakness"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.combat.SelfTrap"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.combat.HoleFill"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.player.AutoReplenish"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.visuals.StorageESP"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.movement.AutoWalk"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.combat.AutoTrap"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.combat.AutoWeb"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.player.ChestStealer"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.misc.AutoReconnect"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.player.PortalChat"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.combat.AntiBed"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.player.SpeedMine"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.player.Offhand"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.visuals.PortalESP"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.misc.AutoEZ"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.movement.BoatFly"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.combat.AutoClicker"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.combat.BowSpam"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.player.LiquidInteract"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.player.PacketExp"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.player.AntiHunger"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.visuals.NewChunks"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.misc.AntiAFK"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.combat.AutoCity"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.combat.AntiCev"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.misc.StashFinder"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.player.AutoKit"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.player.EChestFarmer"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.player.InventorySorter"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.combat.Blocker"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.combat.Burrow"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.player.NoRotate"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.movement.FastLadder"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.player.AutoFish"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.player.AutoMount"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.visuals.ChorusPredict"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.movement.EntityControl"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.player.FastPlace"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.player.AutoTunnel"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.movement.AnchorFly"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.combat.BowBomb"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.movement.PacketFly"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.combat.AntiRegear"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.player.AutoHighway"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.visuals.LogoutSpots"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.player.PortalGodMode"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.player.MultiTask"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.combat.AntiTotem"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.combat.FeetPlace"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.combat.HoleMiner"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.combat.CevBreaker"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.player.AutoPotion"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.player.AutoSoup"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.player.ChorusExploit"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.movement.Spider"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.movement.HighJump"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.movement.AutoSneak"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.player.FastDrop"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.visuals.FreeLook"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.misc.AutoBreed"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.misc.AutoShear"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.movement.LongJump"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.visuals.Breadcrumbs"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.misc.MiddleClickFriend"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.player.InvCleaner"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.MODULE)
                .contains("combatant.client.features.module.modules.misc.AutoSign"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.COMMAND)
                .contains("combatant.client.features.command.impl.VClipCommand"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.COMMAND)
                .contains("combatant.client.features.command.impl.HClipCommand"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.COMMAND)
                .contains("combatant.client.features.command.impl.ClearChatCommand"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.COMMAND)
                .contains("combatant.client.features.command.impl.RawChatCommand"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.SOUND)
                .contains("combatant.client.features.gui.hud.draggable.impl.HudNotifier$NotificationSound"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.ASSET_HOOK)
                .contains("combatant.client.util.sound.SoundSystem"));
        assertTrue(CombatantIndex.classNames(CombatantIndex.Kind.CONFIG)
                .contains("combatant.client.features.relations.PlayerRelations"));
    }

    @Test
    void packageFilterDoesNotLeakOtherComponentPackages() {
        assertTrue(CombatantIndex.classNames(
                        CombatantIndex.Kind.COMMAND,
                        "combatant.client.features.command.impl"
                ).stream()
                .allMatch(name -> name.startsWith("combatant.client.features.command.impl.")));
    }
}
